const RightSection = () => {
    return (
        <div className="flex-1">
            <div>right section</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>
            <div>Right sesction</div>

        </div>
    )
}

export default RightSection
